/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thingmagic_SerialTransportNative */

#ifndef _Included_com_thingmagic_SerialTransportNative
#define _Included_com_thingmagic_SerialTransportNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thingmagic_SerialTransportNative
 * Method:    nativeInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_thingmagic_SerialTransportNative_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_thingmagic_SerialTransportNative
 * Method:    nativeCreate
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_thingmagic_SerialTransportNative_nativeCreate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_thingmagic_SerialTransportNative
 * Method:    nativeOpen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_thingmagic_SerialTransportNative_nativeOpen
  (JNIEnv *, jobject);

/*
 * Class:     com_thingmagic_SerialTransportNative
 * Method:    nativeSendBytes
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_com_thingmagic_SerialTransportNative_nativeSendBytes
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     com_thingmagic_SerialTransportNative
 * Method:    nativeReceiveBytes
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_com_thingmagic_SerialTransportNative_nativeReceiveBytes
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     com_thingmagic_SerialTransportNative
 * Method:    nativeSetBaudRate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_thingmagic_SerialTransportNative_nativeSetBaudRate
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_thingmagic_SerialTransportNative
 * Method:    nativeGetBaudRate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_thingmagic_SerialTransportNative_nativeGetBaudRate
  (JNIEnv *, jobject);

/*
 * Class:     com_thingmagic_SerialTransportNative
 * Method:    nativeShutdown
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_thingmagic_SerialTransportNative_nativeShutdown
  (JNIEnv *, jobject);

/*
 * Class:     com_thingmagic_SerialTransportNative
 * Method:    nativeFlush
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_thingmagic_SerialTransportNative_nativeFlush
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
